---
# The purpose of this file is to define envrionment-specific parameters for the
# ceph client
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: tenant-ceph-client
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: tenant-ceph-client-global
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  values:
    conf:
      pool:
        target:
          osd: 12
...
