---
schema: armada/ChartGroup/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-drydock-scaled
  layeringDefinition:
    abstract: false
    layer: type
  storagePolicy: cleartext
data:
  description: Drydock
  chart_group:
    - ucp-maas-scaled
    - ucp-drydock
