---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-maas-scaled
  layeringDefinition:
    abstract: false
    layer: type
    parentSelector:
      name: ucp-maas-global
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
  substitutions:
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .vip.maas_vip
      dest:
        path: .values.network.maas_ingress.addr
data:
  values:
    pod:
      replicas:
        region: 2
        rack: 2
...
