heat_template_version: ocata

parameters:
  network_name:
    type: string
    default: public

  physical_network_name:
    type: string
    default: ovsnet

  vlan_id:
    type: string
    default: 1153

  subnet_name:
    type: string
    default: public

  subnet_cidr:
    type: string
    default: 10.10.155.0/24

  subnet_gateway:
    type: string
    default: 10.10.155.1

  subnet_pool_start:
    type: string
    default: 10.10.155.29

  subnet_pool_end:
    type: string
    default: 10.10.155.99

resources:
  public_net:
    type: OS::Neutron::ProviderNet
    properties:
      admin_state_up: true
      name:
        get_param: network_name
      network_type: vlan
      physical_network:
        get_param: physical_network_name
      segmentation_id:
        get_param: vlan_id
      port_security_enabled: true
      router_external: false
      shared: true

  private_subnet:
    type: OS::Neutron::Subnet
    properties:
      name:
        get_param: subnet_name
      network:
        get_resource: public_net
      cidr:
        get_param: subnet_cidr
      gateway_ip:
        get_param: subnet_gateway
      enable_dhcp: true
      allocation_pools:
        - start:
            get_param: subnet_pool_start
          end:
            get_param: subnet_pool_end
      dns_nameservers:
        - 10.10.155.20
