---
# This file defines site-specific deviations for MaaS.
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-maas
  layeringDefinition:
    abstract: false
    layer: type
    parentSelector:
      name: ucp-maas-global
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
  substitutions:
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .vip.maas_vip
      dest:
        path: .values.network.maas_ingress.addr
data: {}
...
