---
schema: nc/CorridorConfig/v1
metadata:
  schema: metadata/Document/v1
  name: corridor-config
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      corridor: '1'
      region: 'anuket-laas'
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  corridor: 'C-L01'
  infrastructure:
    dns:
      upstream_servers:
        - 10.200.139.8      
      # Repeat the same values as above, but formatted as a common separated
      # string
      upstream_servers_joined: 10.200.139.8
...
