---
# This file defines hardware-specific settings for neutron. If you use the same
# hardware profile as this environment, you should not need to change this file.
# Otherwise, you should review the settings here and adjust for your hardware.
# In particular:
# 1. logical network interface names
# 2. physical device mappigns
# TODO: Should move to global layer and become tied to the hardware profile
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  replacement: true
  name: neutron
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: neutron-type
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  wait:
    timeout: 1800
  test:
    timeout: 900
  values:
    labels:
      sriov:
        node_selector_key: sriov
        node_selector_value: enabled
    pod:
      security_context:
        neutron_sriov_agent:
          pod:
            runAsUser: 42424
          container:
            neutron_sriov_agent_init:
              privileged: true
              runAsUser: 0
              readOnlyRootFilesystem: false
            neutron_sriov_agent:
              readOnlyRootFilesystem: true
              privileged: true
    network:
      interface:
        sriov:
          - device: eno4
            num_vfs: 32
            promisc: false
      backend:
        - openvswitch
        - sriov
    conf:
      sriov_init:
        - besteffort
      plugins:
        ml2_conf:
          ml2:
            mechanism_drivers: l2population,openvswitch,sriovnicswitch
          ml2_type_vlan:
            ## NOTE: Must have at least 1 sriov network defined
            network_vlan_ranges: external,sriovnet1:100:4000
        sriov_agent:
          securitygroup:
            firewall_driver: neutron.agent.firewall.NoopFirewallDriver
          sriov_nic:
            ## NOTE: Must have at least 1 sriov network to physical device
            ##       mapping, otherwise sriov agent readiness check
            ##       will fail.
            physical_device_mappings: sriovnet1:eno4
            exclude_devices: ""
...
