---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  replacement: true
  name: cinder
  labels:
    name: cinder-type
  layeringDefinition:
    abstract: false
    layer: type
    parentSelector:
      name: cinder-global
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  values:
    pod:
      replicas:
        api: 3
        volume: 3
        scheduler: 3
        backup: 3
...
