---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  replacement: true
  name: glance
  labels:
    name: glance-type
  layeringDefinition:
    abstract: false
    layer: type
    parentSelector:
      name: glance-global
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  values:
    conf:
      rally_tests:
        run_tempest: false
        tests:
          GlanceImages.create_and_delete_image:
            - args:
                container_format: bare
                disk_format: qcow2
                image_location: https://download.cirros-cloud.net/0.3.5/cirros-0.3.5-x86_64-disk.img
              runner:
                concurrency: 1
                times: 1
                type: constant
              sla:
                failure_rate:
                  max: 0
          GlanceImages.create_and_list_image:
            - args:
                container_format: bare
                disk_format: qcow2
                image_location: https://download.cirros-cloud.net/0.3.5/cirros-0.3.5-x86_64-disk.img
              runner:
                concurrency: 1
                times: 1
                type: constant
              sla:
                failure_rate:
                  max: 0

...
