---
## NOTE: this file created to test ovs-dpdk
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: nova-ovsdpdk
  labels:
    component: nova
#  replacement: true
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: nova-cntt
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions-ovsdpdk
        path: .charts.osh.nova
      dest:
        path: .source
    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions-ovsdpdk
        path: .images.osh.nova
      dest:
        path: .values.images.tags
data:
  values:
    conf:
      nova:
        pci:
          ## NOTE: Exclude vf0 from each of the sriov nic
          passthrough_whitelist: |
              [{"address": {"domain":"0000","bus":"05","slot":"06","function":"[1-7]"}, "physical_network": "sriovnet1"},{"address": "0000:05:07.*", "physical_network": "sriovnet1"},{"address": "0000:05:08.*", "physical_network": "sriovnet1"},{"address": "0000:05:09.*", "physical_network": "sriovnet1"}]
  dependencies:
    - nova-htk-ovsdpdk
...
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: nova-htk-ovsdpdk
  layeringDefinition:
    abstract: false
    layer: site
  storagePolicy: cleartext
  substitutions:
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions-ovsdpdk
        path: .charts.osh.nova-htk
      dest:
        path: .source
data:
  chart_name: nova-htk
  release: nova-htk
  namespace: nova-htk
  values: {}
  dependencies: []
...
