---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  replacement: true
  name: neutron
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: neutron-cruiserlite
      component: neutron
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  values:
    ## NOTE: "besteffort" helps prevent sriov init script from failing due to the network
    ## card on pod 15 servers (Intel 82599ES) does not support vf true promiscious mode
    ## setting. The "besteffort" flag was originally designed for dev environment and is
    ## not suitable for production environment as it silents all errors during sriov init.
    conf:
      sriov_init:
        - besteffort
      plugins:
        sriov_agent:
          sriov_nic:
            physical_device_mappings: sriovnet1:ens785f1
            exclude_devices: ens785f1:0000:05:10.1; 0000:05:10.3
...
