---
# The purpose of this file is to define the environment-specific public-facing
# VIP for the ingress controller
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ingress-kube-system
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      ingress: kube-system
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
  substitutions:
    - src:
        schema: pegleg/CommonAddresses/v1
        name: common-addresses
        path: .vip.ingress_vip
      dest:
        path: .values.network.vip.addr
data:
  values:
    network:
      ingress:
        disable-ipv6: "true"
      vip:
        manage: true
...
