---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  replacement: true
  name: grafana
  labels:
    name: grafana-type
  layeringDefinition:
    abstract: false
    layer: type
    parentSelector:
      name: grafana-global
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  values:
    pod:
      replicas:
        grafana: 1
...
