---
# OVS-DPDK NOTE:
#   This chart is created to support deployment of ovs-dpdk.
#   Do not use for env that uses regular ovs kernel.

schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: nova-ovsdpdk
  labels:
    name: nova-ovsdpdk-cntt
    component: nova
  layeringDefinition:
    abstract: false
    layer: type
    parentSelector:
      name: nova-global
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .ovs-dpdk.charts.osh.nova
      dest:
        path: .source
    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .ovs-dpdk.images.osh.nova
      dest:
        path: .values.images.tags
    - src:
        schema: drydock/HardwareProfile/v1
        name: intel-s2600wt
        path: .cpu_sets.kvm
      dest:
        path: .values.conf.nova.DEFAULT.vcpu_pin_set
data:
  values:
    pod:
      replicas:
        api_metadata: 3
        compute_ironic: 3
        placement: 3
        osapi: 3
        conductor: 3
        consoleauth: 3
        scheduler: 3
        novncproxy: 3
        spiceproxy: 3
    network:
      backend:
       - openvswitch
       - sriov
    conf:
      nova:
        filter_scheduler:
          available_filters: "nova.scheduler.filters.all_filters"
          enabled_filters:  "RetryFilter,AvailabilityZoneFilter,RamFilter,CoreFilter,DiskFilter,ComputeFilter,ImagePropertiesFilter,ServerGroupAntiAffinityFilter,ServerGroupAffinityFilter,AggregateInstanceExtraSpecsFilter,AggregateCoreFilter,AggregateRamFilter,AggregateMultiTenancyIsolation,JsonFilter,IoOpsFilter,AggregateDiskFilter,AllHostsFilter,IsolatedHostsFilter,AggregateImagePropertiesIsolation,PciPassthroughFilter,AggregateIoOpsFilter,NumInstancesFilter,AggregateNumInstancesFilter,MetricsFilter,SimpleCIDRAffinityFilter,AggregateTypeAffinityFilter,NUMATopologyFilter,ComputeCapabilitiesFilter,DifferentHostFilter,SameHostFilter"
        pci:
          alias: '{"name": "numa0", "capability_type": "pci", "product_id": "154c", "vendor_id": "8086", "device_type": "type-PCI"}'
          ## OVS-DPDK NOTE: Exclude vf0 from each of the sriov nic, vf0 is reserved for used by ovs to create dpdk bond.
          passthrough_whitelist: |
              [{"address": {"domain":"0000","bus":"05","slot":"06","function":"[1-7]"}, "physical_network": "sriovnet1"},{"address": "0000:05:07.*", "physical_network": "sriovnet1"},{"address": "0000:05:08.*", "physical_network": "sriovnet1"},{"address": "0000:05:09.*", "physical_network": "sriovnet1"}]
  dependencies:
    - nova-htk-ovsdpdk
...
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: nova-htk-ovsdpdk
  labels:
    name: nova-htk-ovsdpdk-cntt
    component: nova
  layeringDefinition:
    abstract: false
    layer: type
  storagePolicy: cleartext
  substitutions:
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .ovs-dpdk.charts.osh.nova-htk
      dest:
        path: .source
data:
  chart_name: nova-htk
  release: nova-htk
  namespace: nova-htk
  values: {}
  dependencies: []
...
