---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  replacement: true
  name: osh-infra-mariadb
  labels:
    name: osh-infra-mariadb-type
  layeringDefinition:
    abstract: false
    layer: type
    parentSelector:
      name: osh-infra-mariadb-global
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  values:
    pod:
      replicas:
        server: 1
        ingress: 1
...
