---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: elasticsearch
  labels:
    name: elasticsearch-type
  layeringDefinition:
    abstract: false
    layer: type
    parentSelector:
      hosttype: elasticsearch-global
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  values:
    pod:
      replicas:
        client: 3
      resources:
        enabled: true
        apache_proxy:
          limits:
            memory: "1024Mi"
            cpu: "2000m"
          requests:
            memory: "0"
            cpu: "0"
        client:
          requests:
            memory: "4Gi"
            cpu: "1000m"
          limits:
            memory: "8Gi"
            cpu: "2000m"
        master:
          requests:
            memory: "4Gi"
            cpu: "1000m"
          limits:
            memory: "8Gi"
            cpu: "2000m"
        data:
          requests:
            memory: "4Gi"
            cpu: "1000m"
          limits:
            memory: "8Gi"
            cpu: "2000m"
        prometheus_elasticsearch_exporter:
          requests:
            memory: "0"
            cpu: "0"
          limits:
            memory: "1024Mi"
            cpu: "2000m"

    storage:
      requests:
        storage: 10Gi
    conf:
      elasticsearch:
        env:
          java_opts:
            client: "-Xms2048m -Xmx2048m"
            data: "-Xms2048m -Xmx2048m"
            master: "-Xms2048m -Xmx2048m"
...
