---
schema: nc/CorridorConfig/v1
metadata:
  schema: metadata/Document/v1
  name: corridor-config
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      corridor: '1'
      region: 'global'
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  corridor: 'c17'
  infrastructure:
    dns:
      upstream_servers:
        - 10.10.170.20
        - 10.10.171.20
      # Repeat the same values as above, but formatted as a common separated
      # string
      upstream_servers_joined: 10.10.170.20, 10.10.171.20
...
