---
# OVS-DPDK NOTE:
#   This chart is created to support deployment of ovs-dpdk.
#   Do not use for env that uses regular ovs kernel.
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: libvirt-ovsdpdk
  labels:
    name: libvirt-ovsdpdk-cntt
    component: libvirt
  layeringDefinition:
    abstract: false
    layer: type
    parentSelector:
      name: libvirt-global
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
  substitutions:
    # Chart source
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.osh.libvirt
      dest:
        path: .source
    # Images
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .ovs-dpdk.images.osh.libvirt
      dest:
        path: .values.images.tags
data:
  values:
    network:
      backend:
        - openvswitch
        - sriov
  dependencies:
    - libvirt-htk-ovsdpdk
...
---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: libvirt-htk-ovsdpdk
  labels:
    name: libvirt-htk-ovsdpdk-cntt
    component: libvirt
  layeringDefinition:
    abstract: false
    layer: type
  storagePolicy: cleartext
  substitutions:
    - src:
        schema: pegleg/SoftwareVersions/v1
        name: software-versions
        path: .charts.osh.libvirt-htk
      dest:
        path: .source
data:
  chart_name: libvirt-htk
  release: libvirt-htk
  namespace: libvirt-htk
  values: {}
  dependencies: []
...
