---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: libvirt
  replacement: true
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: libvirt-global
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  values:
    network:
      backend:
        - openvswitch
        - sriov
...
