---
# This file defines hardware-specific settings for neutron. If you use the same
# hardware profile as this environment, you should not need to change this file.
# Otherwise, you should review the settings here and adjust for your hardware.
# In particular:
# 1. logical network interface names
# 2. physical device mappigns
# TODO: Should move to global layer and become tied to the hardware profile
# NOTE: Add sriov specific setting here for now, they are dormant until
#       sriov-agent is enabled, which will be done at site level for now.
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  replacement: true
  name: neutron
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: neutron-global
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  wait:
    timeout: 1800
  test:
    timeout: 900
  values:
    ## TODO: put nodeSelctor label here as placeholder
    ##       should be moved to site level later.
    ##       Uncomment to enable sriov in your env.
    labels:
      sriov:
        node_selector_key: sriov
        node_selector_value: enabled
    pod:
      security_context:
        neutron_sriov_agent:
          pod:
            runAsUser: 42424
          container:
            neutron_sriov_agent_init:
              privileged: true
              runAsUser: 0
              readOnlyRootFilesystem: false
            neutron_sriov_agent:
              readOnlyRootFilesystem: true
              privileged: true
    network:
      interface:
        sriov:
          ## NOTE: device name is site specific
          - device: ens785f1
            num_vfs: 32
            promisc: false
      backend:
        - openvswitch
        - sriov
    conf:
      plugins:
        ml2_conf:
          ml2:
            mechanism_drivers: l2population,openvswitch,sriovnicswitch
          ml2_type_vlan:
            ## NOTE: sriovnet vlan range is arbituary
            network_vlan_ranges: external,sriovnet1:100:4000
        sriov_agent:
          securitygroup:
            firewall_driver: neutron.agent.firewall.NoopFirewallDriver
          sriov_nic:
            physical_device_mappings: sriovnet1:ens785f1
            exclude_devices: ""
...
