---
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: neutron
  labels:
    name: neutron-type
  layeringDefinition:
    abstract: false
    layer: type
    parentSelector:
      name: neutron-global
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  values:
    pod:
      replicas:
        server: 9
...
