---
# This file defines hardware-specific settings for nova. If you use the same
# hardware profile as this environment, you should not need to change this file.
# Otherwise, you should review the settings here and adjust for your hardware.
# In particular:
# 1. vcpu_pin_set will change if the number of logical CPUs on the hardware
#    changes.
# 2. pci alias / passthrough_whitelist could change if the NIC type or NIC
#    slotting changes.
# TODO: Should move to global layer and become tied to the hardware profile
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: nova
  labels:
    name: nova-cntt
    component: nova
  layeringDefinition:
    abstract: false
    layer: type
    parentSelector:
      name: nova-global
      component: nova
    actions:
      - method: merge
        path: .
  storagePolicy: cleartext
  substitutions:
    - src:
        schema: drydock/HardwareProfile/v1
        name: intel-s2600wt
        path: .cpu_sets.kvm
      dest:
        path: .values.conf.nova.DEFAULT.vcpu_pin_set
data:
  values:
    network:
      backend:
       - openvswitch
       - sriov
    conf:
      nova:
        filter_scheduler:
          available_filters: "nova.scheduler.filters.all_filters"
          enabled_filters:  "RetryFilter,AvailabilityZoneFilter,RamFilter,CoreFilter,DiskFilter,ComputeFilter,ImagePropertiesFilter,ServerGroupAntiAffinityFilter,ServerGroupAffinityFilter,AggregateInstanceExtraSpecsFilter,AggregateCoreFilter,AggregateRamFilter,AggregateMultiTenancyIsolation,JsonFilter,IoOpsFilter,AggregateDiskFilter,AllHostsFilter,IsolatedHostsFilter,AggregateImagePropertiesIsolation,PciPassthroughFilter,AggregateIoOpsFilter,NumInstancesFilter,AggregateNumInstancesFilter,MetricsFilter,SimpleCIDRAffinityFilter,AggregateTypeAffinityFilter,NUMATopologyFilter,ComputeCapabilitiesFilter,DifferentHostFilter,SameHostFilter"
        pci:
          alias: '{"name": "numa0", "capability_type": "pci", "product_id": "154c", "vendor_id": "8086", "device_type": "type-PCI"}'
          passthrough_whitelist: |
              [{"address": "0000:05:06.*", "physical_network": "sriovnet1"},{"address": "0000:05:07.*", "physical_network": "sriovnet1"},{"address": "0000:05:08.*", "physical_network": "sriovnet1"},{"address": "0000:05:09.*", "physical_network": "sriovnet1"}]
...
